- name: Check for netplan configuration files
  ansible.builtin.find:
    paths: /etc/netplan
    patterns: "*.yaml"
  register: netplan_files

- name: Backup and modify netplan configs if they exist
  when: netplan_files.matched > 0
  block:
    - name: Disable cloud-init network configuration
      ansible.builtin.copy:
        content: |
          network: {config: disabled}
        dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
        mode: '0600'
      become: true

- name: Deploy netplan configuration from template
  ansible.builtin.template:
    src: 99-netplan-scionwan.yaml.j2 
    dest: /etc/netplan/99-netplan-scionwan.yaml 
    mode: '0600'
  become: true

- name: Check if 50-cloud-init.yaml exists
  ansible.builtin.stat:
    path: /etc/netplan/50-cloud-init.yaml
  register: netplan_file

- name: Rename cloud-init netplan file so it won't be processed
  ansible.builtin.command: mv /etc/netplan/50-cloud-init.yaml /etc/netplan/50-cloud-init.yaml.disabled
  become: true
  when: netplan_file.stat.exists

- name: Apply netplan configuration
  ansible.builtin.command: netplan apply
  become: true