- name: Ensure bridge interface exists
  ansible.builtin.command: ip link add name scionwan type bridge
  ignore_errors: true
  become: true

- name: Bring up bridge interface
  ansible.builtin.command: ip link set scionwan up
  become: true

- name: Copy bridge script template to remote server
  ansible.builtin.template:
    src: bridge_toggle.sh.j2
    dest: /usr/local/sbin/bridge_toggle.sh
    mode: '0755'
  become: true

- name: Execute bridge attach
  ansible.builtin.command: /usr/local/sbin/bridge_toggle.sh attach
  become: true

- name: Check for netplan configuration files
  ansible.builtin.find:
    paths: /etc/netplan
    patterns: "*.yaml"
  register: netplan_files
  become: true
- name: Backup and modify netplan configs if they exist
  when: netplan_files.matched > 0
  block:
    - name: Disable cloud-init network configuration
      ansible.builtin.copy:
        content: |
          network: {config: disabled}
        dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
        mode: '0644'
      become: true