#
# This a Netplan configuration file used to create the "scionwan" bridged network used by the Edge VM appliance on a Sui Fullnode/Validator
# 
# Copy this file as /etc/netplan/55-scionwan.yaml
# change the interface name [eno1] to match your interface
# add in the IPv4 and/or IPv6 address under "addresses"
# add in the IPv4 and/or IPv6 default gateways under "routes"
# remove the IPv4 and/or IPv6 addresses and routes from the existing interface on the existing netplan configuration file
#
# run "netplan apply" to create the bridge
#
# This configuration has been tested on Ubuntu 24
#
#
network:
    bridges:
      scionwan:
        dhcp4: no
        dhcp6: no
        interfaces: [eno1]
        addresses:
          - 10.0.0.2/31
          - 2001:0DB8::/32
        routes:
          - to: default
            via: 10.0.0.1
          - to: default
            via: 2001:0DB8::1
        nameservers:
          addresses:
          - 8.8.8.8
          - 1.1.1.1
          - 2001:4860:4860::8888
          - 2606:4700:4700::1111
    version: 2
