---
- name: Create WireGuard config directory
  ansible.builtin.file:
    path: "{{ wireguard_config_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Load CIDR ranges from YAML
  set_fact:
    scion_cidr_ranges: "{{ lookup('file', 'advertised_ip_ranges.yml') | from_yaml }}"

- name: Configure WireGuard interface
  ansible.builtin.template:
    src: wireguard.conf.j2
    dest: "{{ wireguard_config_path }}/{{ wireguard_interface }}.conf"
    owner: root
    group: root
    mode: '0600'
  vars:
    allowed_ips: "{{ scion_cidr_ranges | flatten_cidr_ranges(wireguard.peer.allowed_ips) | join(', ') }}"
  become: true

- name: Enable and start WireGuard interface
  ansible.builtin.systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    enabled: true
    state: started
  become: true
