
- name: Create WireGuard config directory
  ansible.builtin.file:
    path: "{{ wireguard_config_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure WireGuard interface
  ansible.builtin.template:
    src: wireguard.conf.j2
    dest: "{{ wireguard_config_path }}/{{ wireguard_interface }}.conf"
    owner: root
    group: root
    mode: '0600'

- name: Enable and start WireGuard interface
  ansible.builtin.systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    enabled: true
    state: started