---
- name: Configure the VM host and deploy the EDGE VM
  hosts: bare_metal_hosts
  gather_facts: false
  vars_files:
    - "{{ deployment_package_config }}"
  environment:
    # All libvirt operations are done to the system-level service.
    LIBVIRT_DEFAULT_URI: "qemu:///system"
  roles:
    - role: deploy_edge_metal
      deploy_edge_metal_public_interface: "{{ public_interface }}"
      deploy_edge_metal_ssh_keys: "{{ ssh_authorized_keys }}"
      deploy_edge_metal_download: "{{ package_edge_download }}"

    - role: routing_to_edge
      when: 
        - deployment_type is defined
        - deployment_type == "dedicated"
      routing_to_edge_interface: "{{ bgp_if_name | default(public_interface) }}"
      routing_to_edge_addresses:
        - "fd00:05c1:0400::1/126"
        - "192.168.17.1/30"
      routing_to_edge_edge_ipv4: "192.168.17.2"
