---
- name: Configure the EDGE appliance
  hosts: edge
  gather_facts: false
  vars_files:
    - "{{ deployment_package_path }}/config.yml"
  vars:
    host_ipv4: "{{ hostvars['bare-metal']['public_ipv4'] }}"
  roles:
    - role: edge
      edge_isd_as: "{{ package_isd_as }}"
      edge_issuer_isd_as: "{{ package_issuer_isd_as }}"
      edge_scion_name: "{{ package_common_name }}"

      edge_trcs_dir: "{{ trcs_path }}"
      edge_key_local_path: "{{ as_private_key_path }}"
      edge_cert_local_path: "{{ as_certificate_path }}"

      edge_router_internal_port: 30999
      edge_forwarding_key: "{{ lookup('ansible.builtin.file', forwarding_key_path) }}"

      # --- The following variables are static for the deployment configuration.
      # IP address on which the EDGE VM is contacted from the host.
      edge_internal_ipv4: "{{ public_network.ipv4_cidr | ansible.utils.ipaddr('address') }}"
      # IP address that the EDGE VM can use to contact the host.
      edge_bgp_neighbor_address: "{{ host_ipv4 }}"

      edge_ethernets:
        - name: enp1s0
          addresses:
            - 169.254.1.2/24
          driver: LINUX
        # Interface for speaking with the remote EDGE, host, as well as the public internet.
        - name: enp5s0
          gateway:
            ipv4_gateway: "{{ public_network.gateway }}"
          addresses:
            - "{{ public_network.ipv4_cidr }}"
          driver: VPP_DPDK

      edge_neighbors: "{{ package_scion_neighbors }}"
      edge_advertised_ranges: "{{ scion_validator_cidr_map }}"

# Use resolved and reboot
#
# in /etc/systemd/system/host-route.service and enable
# [Unit]
# Description=Host route enp5s0
# BindsTo=sys-subsystem-net-devices-enp5s0.device
# After=sys-subsystem-net-devices-enp5s0.device
#
# [Service]
# Type=oneshot
# RemainAfterExit=yes
# ExecStart=/usr/bin/ip route add 103.88.234.53 dev enp5s0
# ExecStop=/usr/bin/ip route del 103.88.234.53 dev enp5s0
#
# [Install]
# WantedBy=sys-subsystem-net-devices-enp5s0.device
#
# in /etc/systemd/resolved.conf.d/manual.conf
# [Resolve]
# DNS=8.8.8.8 1.1.1.1

- name: Configure routing on associated Sui nodes
  hosts: bare-metal
  gather_facts: false
  vars:
    edge_vars: "{{ hostvars[associated_edge] }}"
  roles:
    - role: routing_to_edge
      routing_to_edge_interface: "{{ public_iface }}"
      routing_to_edge_edge_ipv4: "{{ hostvars['edge']['public_ipv4'] }}"
