---
all:
  vars:
    # Directory in which secret values are stored on the controller
    secrets_dir: "{{ playbook_dir }}/../secrets"
    # Directory of the deployment package provided by Mysten Labs
    deployment_package_path: "{{ playbook_dir }}/../deployment-package"

    # Paths derived from the above
    deployment_package_config: "{{ deployment_package_path }}/config.yml"
    scion_forwarding_key_path: "{{ secrets_dir }}/forwarding-key.key"
    scion_private_key_path: "{{ secrets_dir }}/scion-private-key.key"
    scion_trcs_path: "{{ deployment_package_path }}/trcs"
    scion_certificate_path: "{{ deployment_package_path }}/scion-cert.pem"

  hosts:
    bare_metal:
      # -- SSH options
      ansible_host: 103.88.234.53
      ansible_user: ubuntu

      # -- Configuration
      # Public interface that will be shared with the EDGE VM
      public_interface: eno1
      # Public IPv4 address of the bare-metal host
      public_ipv4: "{{ ansible_host }}"
      # SSH authorized keys that added to the EDGE VM. Requires at least 1.
      ssh_authorized_keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK/ALpkZY66QR/uYrn4g9/GAjOM5cJ2lKbZrzzMhAg7X jean-pierre@mystenlabs.com"

    edge_vm:
      # -- SSH options
      # Uses the bare-metal as a jump host to SSH into the hosted EDGE VM, does not need to be changed.
      ansible_user: anapaya
      ansible_host: 169.254.1.2
      ansible_ssh_common_args: "-J {{ hostvars['bare_metal']['ansible_user'] ~ '@' ~ hostvars['bare_metal']['ansible_host'] }}"

      # -- Configuration
      network_config:
        ipv4_cidr: 103.88.234.245/31
        gateway: 103.88.234.244
      # Public IPv4 address to be configured on the EDGE.
      public_ipv4: "{{ network_config.ipv4_cidr | ansible.utils.ipaddr('address') }}"
