---
all:
  vars:
    # Directory in which secret values are stored on the controller
    secrets_dir: "{{ playbook_dir }}/../secrets"
    # -- Paths derived from the above path
    forwarding_key_path: "{{ secrets_dir }}/forwarding-key.key"
    as_private_key_path: "{{ secrets_dir }}/scion-private-key.key"

    # Directory of the deployment package provided by Mysten Labs
    deployment_package_path: "{{ playbook_dir }}/../deployment-package"
    # -- Paths derived from the above
    trcs_path: "{{ deployment_package_path }}/trcs"
    as_certificate_path: "{{ deployment_package_path }}/scion-cert.pem"

    scion_validator_cidr_map:
      - isd_as: 17-ffaa:1:ebb
        cidr_ranges:
          - 103.88.234.245/32

      - isd_as: 18-ffaa:1:ebc
        cidr_ranges:
          - 209.250.237.149/32

  hosts:
    bare-metal:
      # -- SSH options
      ansible_host: 103.88.234.53
      ansible_user: ubuntu

      # -- Configuration
      public_ipv4: "{{ ansible_host }}"
      public_iface: eno1
      ssh_authorized_keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK/ALpkZY66QR/uYrn4g9/GAjOM5cJ2lKbZrzzMhAg7X jean-pierre@mystenlabs.com"

    edge:
      ansible_user: anapaya
      ansible_host: 169.254.1.2
      ansible_ssh_common_args: "-J {{ hostvars['bare-metal']['ansible_user'] ~ '@' ~ hostvars['bare-metal']['ansible_host'] }}"

      public_network:
        ipv4_cidr: 103.88.234.245/31
        gateway: 103.88.234.244

      public_ipv4: "{{ public_network.ipv4_cidr | ansible.utils.ipaddr('address') }}"

# TODO(jsmith): The Gateway trafficmatchers may work in this scenario, since we can forward data from the EDGE,
# this would reduce the risk of misconfiguration to just Sui
