---
- name: Run the playbook to setup the host metal.
  ansible.builtin.import_playbook: bare_metal_edge_host.yml

- name: Run the playbook to setup the EDGE.
  ansible.builtin.import_playbook: edge.yml
