---
- name: Configure bare metal host to use wireguard
  hosts: bare_metal_hosts
  gather_facts: true
  roles:
    - role: wireguard
  vars:
    wireguard_interface: "wg0"
    wireguard_private_key: "{{ wireguard.interface.private_key }}"
    wireguard_public_key: "{{ wireguard.peer.public_key }}"
    wireguard_allowed_ips: "{{ wireguard.peer.allowed_ips }}"
    wireguard_endpoint: "{{ wireguard.peer.endpoint }}"
    wireguard_persistent_keepalive: "{{ wireguard.peer.persistent_keepalive }}"
    wireguard_config_path: "/etc/wireguard"
